components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    PriorityEnum:
      enum:
      - low
      - medium
      - high
      title: PriorityEnum
      type: string
    RowRead:
      properties:
        assignee_id:
          anyOf:
          - format: uuid
            type: string
          - type: 'null'
          title: Assignee Id
        created_at:
          format: date-time
          title: Created At
          type: string
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - format: date-time
            type: string
          - type: 'null'
          title: Due Date
        id:
          format: uuid
          title: Id
          type: string
        name:
          title: Name
          type: string
        order:
          title: Order
          type: integer
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
        table_id:
          format: uuid
          title: Table Id
          type: string
        updated_at:
          format: date-time
          title: Updated At
          type: string
      required:
      - id
      - table_id
      - name
      - description
      - status
      - priority
      - assignee_id
      - due_date
      - order
      - created_at
      - updated_at
      title: RowRead
      type: object
    StatusEnum:
      enum:
      - todo
      - in_progress
      - done
      title: StatusEnum
      type: string
    TableCreate:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        name:
          title: Name
          type: string
      required:
      - name
      title: TableCreate
      type: object
    TableRead:
      properties:
        board_id:
          description: Foreign key for board
          format: uuid
          title: Board Id
          type: string
        created_at:
          description: Table creation date
          format: date-time
          title: Created At
          type: string
        description:
          anyOf:
          - type: string
          - type: 'null'
          description: Table description
          title: Description
        id:
          description: Primary key for table
          format: uuid
          title: Id
          type: string
        name:
          description: Table name
          title: Name
          type: string
        order:
          description: Table order
          title: Order
          type: integer
        rows:
          description: List of rows in the table
          items:
            $ref: '#/components/schemas/RowRead'
          title: Rows
          type: array
        updated_at:
          description: Table update date
          format: date-time
          title: Updated At
          type: string
        version:
          description: Table version
          title: Version
          type: integer
      required:
      - id
      - board_id
      - name
      - description
      - order
      - version
      - created_at
      - updated_at
      - rows
      title: TableRead
      type: object
    TableUpdate:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        order:
          anyOf:
          - type: integer
          - type: 'null'
          title: Order
        version:
          title: Version
          type: integer
      required:
      - version
      title: TableUpdate
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Monday Lite API
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/v1/boards/{board_id}/tables/:
    get:
      description: List all tables
      operationId: list_tables
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TableRead'
                title: Response List Tables Api V1 Boards  Board Id  Tables  Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: List Tables
      tags:
      - - table
    post:
      description: Create a new table
      operationId: create_table
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableCreate'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Table
      tags:
      - - table
  /api/v1/boards/{board_id}/tables/{table_id}:
    delete:
      description: Delete a table by ID
      operationId: delete_table
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      - in: path
        name: table_id
        required: true
        schema:
          format: uuid
          title: Table Id
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Table
      tags:
      - - table
    put:
      description: Update a table by ID
      operationId: update_table
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      - in: path
        name: table_id
        required: true
        schema:
          format: uuid
          title: Table Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableUpdate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Table
      tags:
      - - table
