version: '3.9'
services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3578
      - POSTGRES_DB=unicorn
    ports: ['5432:5432']
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U  postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis_container
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/cache:/data
    command: redis-server --loglevel warning
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5

  api:
    container_name: api
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    env_file:
      - ../.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=unicorn
      - DB_USER=postgres
      - DB_PASS=3578
      - DATABASE_URL=postgresql://postgres:3578@postgres:5432/unicorn

    volumes:
      - ../apps/api:/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:8000/api/v1/health || exit 1']
      interval: 30s
      retries: 5
      timeout: 10s

volumes:
  db_data:
