version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3578
      - POSTGRES_DB=mondaylite
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports: ["6379:6379"]

  api:
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../apps/api:/code
    depends_on: [db, redis]
    ports: ["8000:8000"]

  web:
    build:
      context: ../
      dockerfile: apps/web/Dockerfile
    command: pnpm dev --host 0.0.0.0 --port 5173
    volumes:
      - ../apps/web:/code
    depends_on: [api]
    ports: ["5173:5173"]

volumes:
  db_data:
    driver: local
