"""Added initial table

Revision ID: 09f8a0df3cfc
Revises: fd52d7d88d4d
Create Date: 2025-08-08 19:06:31.630700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09f8a0df3cfc"
down_revision: Union[str, None] = "fd52d7d88d4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refreshtokens", "is_deleted")
    op.drop_column("rows", "is_deleted")
    op.drop_column("tables", "is_deleted")
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tables",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rows", sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "refreshtokens",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
