components:
  schemas:
    BoardCreate:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        name:
          title: Name
          type: string
      required:
      - name
      title: BoardCreate
      type: object
    BoardRead:
      properties:
        created_at:
          format: date-time
          title: Created At
          type: string
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        id:
          format: uuid
          title: Id
          type: string
        name:
          title: Name
          type: string
        order:
          title: Order
          type: integer
        owner_id:
          format: uuid
          title: Owner Id
          type: string
        updated_at:
          format: date-time
          title: Updated At
          type: string
      required:
      - id
      - name
      - description
      - order
      - owner_id
      - created_at
      - updated_at
      title: BoardRead
      type: object
    BoardUpdate:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        order:
          anyOf:
          - type: integer
          - type: 'null'
          title: Order
      title: BoardUpdate
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Monday Lite API
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/v1/boards/:
    get:
      operationId: list_boards
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BoardRead'
                title: Response List Boards Api V1 Boards  Get
                type: array
          description: Successful Response
      summary: List Boards
      tags:
      - - board
    post:
      operationId: create_board
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardCreate'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Board
      tags:
      - - board
  /api/v1/boards/members/{user_id}:
    delete:
      operationId: remove_member
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          title: User Id
          type: string
      - in: query
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Remove Member
      tags:
      - - board
  /api/v1/boards/{board_id}:
    delete:
      operationId: delete_board
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Board
      tags:
      - - board
    get:
      operationId: get_board
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Board
      tags:
      - - board
    put:
      operationId: update_board
      parameters:
      - in: path
        name: board_id
        required: true
        schema:
          format: uuid
          title: Board Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardUpdate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Board
      tags:
      - - board
