components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    PriorityEnum:
      enum:
      - low
      - medium
      - high
      title: PriorityEnum
      type: string
    RowCreate:
      properties:
        assignee_id:
          anyOf:
          - format: uuid
            type: string
          - type: 'null'
          title: Assignee Id
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - format: date-time
            type: string
          - type: 'null'
          title: Due Date
        name:
          title: Name
          type: string
        position:
          anyOf:
          - type: integer
          - type: 'null'
          title: Position
        priority:
          $ref: '#/components/schemas/PriorityEnum'
          default: medium
        status:
          $ref: '#/components/schemas/StatusEnum'
          default: todo
      required:
      - name
      title: RowCreate
      type: object
    RowRead:
      properties:
        assignee_id:
          anyOf:
          - format: uuid
            type: string
          - type: 'null'
          title: Assignee Id
        created_at:
          format: date-time
          title: Created At
          type: string
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - format: date-time
            type: string
          - type: 'null'
          title: Due Date
        id:
          format: uuid
          title: Id
          type: string
        name:
          title: Name
          type: string
        order:
          title: Order
          type: integer
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
        table_id:
          format: uuid
          title: Table Id
          type: string
        updated_at:
          format: date-time
          title: Updated At
          type: string
      required:
      - id
      - table_id
      - name
      - description
      - status
      - priority
      - assignee_id
      - due_date
      - order
      - created_at
      - updated_at
      title: RowRead
      type: object
    RowUpdate:
      properties:
        assignee_id:
          anyOf:
          - format: uuid
            type: string
          - type: 'null'
          title: Assignee Id
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - format: date-time
            type: string
          - type: 'null'
          title: Due Date
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        position:
          anyOf:
          - type: integer
          - type: 'null'
          title: Position
        priority:
          anyOf:
          - $ref: '#/components/schemas/PriorityEnum'
          - type: 'null'
        status:
          anyOf:
          - $ref: '#/components/schemas/StatusEnum'
          - type: 'null'
      title: RowUpdate
      type: object
    StatusEnum:
      enum:
      - todo
      - in_progress
      - done
      title: StatusEnum
      type: string
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Monday Lite API
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/v1/boards/{board_id}/tables/{table_id}/rows/:
    post:
      operationId: create_row
      parameters:
      - in: path
        name: table_id
        required: true
        schema:
          format: uuid
          title: Table Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RowCreate'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RowRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Row
      tags:
      - - row
  /api/v1/boards/{board_id}/tables/{table_id}/rows/{row_id}:
    delete:
      operationId: delete_row
      parameters:
      - in: path
        name: table_id
        required: true
        schema:
          format: uuid
          title: Table Id
          type: string
      - in: path
        name: row_id
        required: true
        schema:
          format: uuid
          title: Row Id
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Row
      tags:
      - - row
    put:
      operationId: update_row
      parameters:
      - in: path
        name: table_id
        required: true
        schema:
          format: uuid
          title: Table Id
          type: string
      - in: path
        name: row_id
        required: true
        schema:
          format: uuid
          title: Row Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RowUpdate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RowRead'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Row
      tags:
      - - row
