server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_network_name']
        regex: 'unicorn-net'
        action: keep

      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'

      - source_labels: ['__meta_docker_container_name']
        regex: '/unicorn-(.*)'
        target_label: 'service'
        replacement: '${1}'

      - target_label: 'environment'
        replacement: 'production'

      - target_label: 'job'
        replacement: 'docker'

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            trace_id: trace_id
            user_id: user_id
            method: method
            path: path
            status_code: status_code
            duration_ms: duration_ms
            error_code: error_code

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          trace_id:
          user_id:
          method:
          path:
          error_code:

      - output:
          source: message

  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          environment: production
          __path__: /var/log/app/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            trace_id: trace_id

      - match:
          selector: '{job="app_logs"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| (?P<level>\w+) \| (?P<logger>[\w.]+) \| (?P<message>.*)'

            - labels:
                level:
                logger:

            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'
