name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: apps/api } }
    env:
      DB_USER: test
      DB_PASS: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: testdb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps (main + dev)
        run: poetry install --with dev
      - name: Lint (Ruff)
        run: poetry run ruff check .
      - name: Type-check
        run: poetry run mypy app
      - name: Tests
        run: poetry run pytest

  frontend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: apps/web } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.1 --activate
      - name: Install deps
        run: pnpm install
      - name: Lint (ESLint)
        run: pnpm exec eslint src --ext .ts,.tsx
      - name: Format check
        run: pnpm run format -- --check
      - name: Tests
        run: pnpm run test -- --run
